# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false
before_install:
  - (sudo apt-get -qq update && sudo apt-get install -y python3 python3-pip && sudo pip3 install pandas)
script:
    - julia -e 'using Pkg; Pkg.clone(pwd())'
    - julia -e 'using Pkg; Pkg.build("Pandas")'
    - julia -e 'using Pkg; Pkg.test("Pandas")'
