# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - 0.4
  - nightly
notifications:
  email: false
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("Pandas")'
    - julia -e 'Pkg.test("Pandas")'
